### ISSUE TITLE
Add ability to calculate timezone from lat, long, and timestamp

### ISSUE THREAD

**Issue by jacob-israel-turner** [evansiroky/node-geo-tz#108]
Hello!

One of our requirements is to be able to identify the timezone/offset for a geolocation at a specific point in time in the future.  I don't see a way to do that with this library.

There is a [PHP library](https://github.com/minube/geo-timezone) that references `node-geo-tz` as the inspiration, and they have a calculator method.  Its arguments are `lat`, `long`, and `timestamp`, and it uses those to calculate the timezone at that point in time.

Is this something that could reasonably be added to `node-geo-tz`?

**Comment by evansiroky** [comment]
I am assuming that you are looking for something like the `getLocalDate` method from the [geo-timezone](https://github.com/minube/geo-timezone) PHP library, right? Since JavaScript doesn't yet have a good built-in timezone-aware DateTime library, there are a number of packages that handle this such as [moment-timezone](https://momentjs.com/timezone/). Initially, this package did have the ability to return a moment-timezone object. However, I decided that was too opinionated and therefore, as of [version 4.0.0](https://github.com/evansiroky/node-geo-tz/releases/tag/v4.0.0), that functionality was removed from this library. This library focuses on one thing only which is getting the timezone identifier at a particular GPS coordinate. You will need another package to calculate date and time with that information.

I'll leave this issue open for now in case I misunderstood your request.

**Comment by lirbank** [comment]
You can use `node-geo-tz` to get the TZ from the long/lat and then use `luxon` to get the local date (or datetime), try this: 

```ts
import { DateTime, Info } from 'luxon';

export function getLocalDate(date: Date, tz: string): string | null {
  if (!Info.isValidIANAZone(tz)) {
    return null;
  }

  // NOTE: There is an error in the luxon TS types. This series of commands will
  // return null if the timezone is not valid. But the TS types claim it will
  // always return a string. The isValidIANAZone check above will handle this
  return DateTime.fromJSDate(date).setZone(tz).toISODate();
}
```

**Comment by evansiroky** [comment]
Haven't heard back from the issue author, so I'm closing this.

**Comment by michael-ts** [comment]
@evansiroky  Can you clarify what the recommended way is to convert the text string returned from by `find` to an offset from GMT?  e.g. I need something like "+04:00" not the name of a continent/city.

**Comment by michael-ts** [comment]
@lirbank  I can't get your code to work for me.  In my first test, the tz string I got from geo-tz was "Etc/GMT".  The call to `Info.isValidIANAZone(tz)` returns true, but when I try to call `setZone` on the DateTime object from luxon, I get an object with the following member:

      invalid: Invalid {
          reason: 'unsupported zone',
          explanation: 'the zone "Etc/GMT" is not supported'
     }

**Comment by evansiroky** [comment]
@michael-ts, it sounds like you're on your way to answering your own question. You have to use the timezone identifier string with another datetime library that supports timezone identifiers. It appears you may have a problem with your code that uses luxon, so I don't think this is an issue with this repository anymore.

**Comment by michael-ts** [comment]
@evansiroky  Indeed... at first I was thinking that maybe "Etc/GMT" was not a valid time zone, but I was playing around with it last night and found that `moment-timezone` recognizes it.

**Comment by michael-ts** [comment]
@evansiroky It seems there are issues with other coordinates... this library is returning 'Etc/GMT+3' (UTC offset -180) while Google's API is returning 'America/Godthab' (UTC offset -120) which causes Google Photos to place all my photos taken in GMT+3 interleaved with those taken in GMT+2.  Not sure how to work around this - I was trying to avoid using Google's API so as to not require a network connection.

**Comment by evansiroky** [comment]
@michael-ts please submit another issue that contains the coordinates, expected timezone identifier and the actual timezone identifier returned.

**Comment by michael-ts** [comment]
Thanks @evansiroky , issue 143 submitted : https://github.com/evansiroky/node-geo-tz/issues/143
