### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by dyerw** [evansiroky/node-geo-tz#109]
Hi! We're going to be using this library with our typescript codebase so I was going to make declaration files. If you'd like i can put up a PR to get them into DefinitelyTyped. I just wanted to check in and make sure I wasn't duplicating effort or the maintainers of this package didn't have another plan for TS types. Thanks!

**Comment by evansiroky** [comment]
That would be a welcome addition and I haven't been working on that.

**Comment by lirbank** [comment]
Put this into a file `geo-tz.d.ts` in your project to get typings.

```ts
declare module "geo-tz" {
  export default function (lat: number, lng: number): string[];
}
```

**Comment by wlbrough** [comment]
@evansiroky I submitted a PR for adding type definitions https://github.com/evansiroky/node-geo-tz/pull/112

**Comment by evansiroky** [comment]
I suppose I could have done a better job communicating my thoughts around adding TypeScript. Instead of adding a quick definition file, I wanted to add TypeScript to the entire project and properly include it in releases. However, I felt like that was too high of a bar to ask people to clear, so I sort of stayed silent until I found the time and motivation to add TypeScript everywhere in the project. That should be accomplished in #128.
