### ISSUE TITLE
Use more accurate data source than efele.net

### ISSUE THREAD

**Issue by evansiroky** [evansiroky/node-geo-tz#14]
There are numerous problems with the timezone shapefile provided by efele.net including the omission of territorial waters and not correcting very specific edge cases like West Wendover, NV.  Once a more accurate timezone boundary data source becomes available, begin using that data instead.

**Comment by vkelman** [comment]
Very interesting.
In my C# library I was also using shapefiles from efele.net (as IANA database site has link to it) and was dealing with some limitations. I didn't know how to treat ocean areas which, I believe, don't have tz_id and still not sure about it.
I think ships don't use local time based on latitude, but it was necessary for me, because our system (http://planetrisk.com) tracks **incidents** in various locations, including oceans. Incidents were _usually_ submitted with local time, lat, and long. Our company somehow had a SQL table with GEOMs and corresponding time offsets. So, I used it for ocean areas, where tz_id was not defined. I was ignoring DST for ocean areas; I think it's not defined there.

So, are there better shapefiles than efele.net ones somewhere?

**Comment by evansiroky** [comment]
I'm working on one...  see [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder).

**Comment by evansiroky** [comment]
Fixed with #23
