### ISSUE TITLE
Point below Denmark results in Etc/GMT-1

### ISSUE THREAD

**Issue by simplenotezy** [evansiroky/node-geo-tz#161]
We have the following point:

```ts
{"type":"Point","coordinates":[11.286195963,54.579906023]}
```
And it results in: `Etc/GMT-1` - I would expect it to resolve to `Europe/Copenhagen`.

![image](https://github.com/evansiroky/node-geo-tz/assets/3786627/ddc5bdf6-83b2-4d54-98ca-885a1aad2bde)

![image](https://github.com/evansiroky/node-geo-tz/assets/3786627/1295de31-f8ae-4ee3-90c0-4d87f1947c49)

Not sure if it's related to https://github.com/evansiroky/node-geo-tz/issues/79 ?

**Comment by evansiroky** [comment]
This is expected behavior. The underlying data that this library uses is from [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder/) which notes in the [Limitations of this project section](https://github.com/evansiroky/timezone-boundary-builder/#limitations-of-this-project):

> This project does include timezones in the oceans, but strictly uses territorial waters or Etc/GMT timezones instead of unofficially observed areas such as Exclusive Economic Zones.

The given point falls outside the territorial waters of both Denmark and Germany as seen in the following screenshot:

<img width="413" alt="Screen Shot 2023-06-12 at 5 18 28 PM" src="https://github.com/evansiroky/node-geo-tz/assets/3112493/1e8cefe4-a901-4256-b8a1-ce09b659e59b">

Therefore the lookup of the timezone identifier finds the appropriate ocean zone to return.

**Comment by simplenotezy** [comment]
Interesting, thanks for quick reply Evan. I wonder why that is though, but that's perhaps a question for timezone-boundary-builder
