### ISSUE TITLE
readFileSync issue on some timezone

### ISSUE THREAD

**Issue by ghost** [evansiroky/node-geo-tz#86]
While using this API, I have come across an issue when trying to get some time zones... I am getting "ERROR TypeError: fs.readFileSync is not a function".

I am trying to use this timezone library in my front end in reactjs

Here is another issue related to this:

https://github.com/evansiroky/node-geo-tz/issues/77

**Comment by evansiroky** [comment]
This library does not support browser platforms by design.  This is noted in the README, but is not prominently featured so I will make sure to remedy that.  The reason this library does not support use in browsers is that it does not compress the underlying geographic data (of about 36 MB) so that it is possible to perform exact geographic lookups.
