### ISSUE TITLE
Some regions prevent the script from exiting

### ISSUE THREAD

**Issue by timotejroiko** [evansiroky/node-geo-tz#95]
Hello,

I was running some tests and it seems that some regions prevent the script from properly exiting.

for example, running the following script:
```js
const geoTz = require("geo-tz");
console.log(geoTz(50, 30))
```

returns `['Europe/Kiev']` and exits the script.

but running this:
```js
const geoTz = require("geo-tz");
console.log(geoTz(30, 50))
```

returns `['Asia/Tehran']` and keeps the script running, forcing a Ctrl+C to properly exit the script.

Is this intended? Cheers!

node v12.13.0
npm v6.12.0
geo-tz v5.0.5

**Comment by evansiroky** [comment]
This is most likely due to the use of the package `timed-cache` which is used when a detailed geographic lookup requires loading in extra data from a file. Currently, this always happens and there is no way to turn it off. I could see the usefulness of having a way to turn this feature off. That'd be a good PR that I'd happily review and merge.

**Comment by timotejroiko** [comment]
Ah i thought so. I will look into it and send you a PR. Thanks!
